"""Add graduation_year_source column to leads

Revision ID: 045d801f097e
Revises: 6c56a7154fb1
Create Date: 2025-12-22 05:34:45.629923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045d801f097e'
down_revision: Union[str, Sequence[str], None] = '6c56a7154fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    graduationyearsource = sa.Enum('CSV', 'ESTIMATED', name='graduationyearsource')
    graduationyearsource.create(op.get_bind(), checkfirst=True)
    
    op.add_column('leads', sa.Column(
        'graduation_year_source',
        graduationyearsource,
        nullable=True,
        server_default='CSV'
    ))
    op.execute("UPDATE leads SET graduation_year_source = 'CSV' WHERE graduation_year_source IS NULL")
    op.alter_column('leads', 'graduation_year_source', nullable=False, server_default='CSV')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'graduation_year_source')
    # ### end Alembic commands ###
