"""add_segment_event_status_in_to_scenarios

Revision ID: 5683389a6789
Revises: aec4bf5f60af
Create Date: 2026-01-25 14:40:56.861649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5683389a6789'
down_revision: Union[str, Sequence[str], None] = 'aec4bf5f60af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('segment_event_status_in', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'segment_event_status_in')
    # ### end Alembic commands ###
