"""add_line_messaging_support

Revision ID: 9b87b08ba3f6
Revises: eb4d2695eac7
Create Date: 2025-12-24 08:10:49.671635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b87b08ba3f6'
down_revision: Union[str, Sequence[str], None] = 'eb4d2695eac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    
    bind.execute(sa.text("""
        DO $$ BEGIN
            CREATE TYPE lineidentitystatus AS ENUM ('UNLINKED', 'LINKED');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """))
    bind.execute(sa.text("""
        DO $$ BEGIN
            CREATE TYPE sendchannel AS ENUM ('EMAIL', 'LINE');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """))
    bind.execute(sa.text("""
        DO $$ BEGIN
            CREATE TYPE channeltype AS ENUM ('EMAIL', 'LINE');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """))
    
    bind.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS line_identities (
            id SERIAL PRIMARY KEY,
            line_user_id VARCHAR(50) NOT NULL,
            lead_id INTEGER REFERENCES leads(id),
            status lineidentitystatus NOT NULL DEFAULT 'UNLINKED',
            linked_at TIMESTAMP WITH TIME ZONE,
            display_name VARCHAR(255),
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
        )
    """))
    
    result = bind.execute(sa.text(
        "SELECT 1 FROM pg_indexes WHERE indexname = 'ix_line_identities_lead_id'"
    ))
    if not result.fetchone():
        bind.execute(sa.text("CREATE INDEX ix_line_identities_lead_id ON line_identities (lead_id)"))
    
    result = bind.execute(sa.text(
        "SELECT 1 FROM pg_indexes WHERE indexname = 'ix_line_identities_line_user_id'"
    ))
    if not result.fetchone():
        bind.execute(sa.text("CREATE UNIQUE INDEX ix_line_identities_line_user_id ON line_identities (line_user_id)"))
    
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name = 'leads' AND column_name = 'line_blocked'"
    ))
    if not result.fetchone():
        bind.execute(sa.text("ALTER TABLE leads ADD COLUMN line_blocked BOOLEAN NOT NULL DEFAULT FALSE"))
    
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name = 'send_logs' AND column_name = 'channel'"
    ))
    if not result.fetchone():
        bind.execute(sa.text("ALTER TABLE send_logs ADD COLUMN channel sendchannel NOT NULL DEFAULT 'EMAIL'"))
    
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name = 'send_logs' AND column_name = 'provider_message_id'"
    ))
    if not result.fetchone():
        bind.execute(sa.text("ALTER TABLE send_logs ADD COLUMN provider_message_id VARCHAR(255)"))
    
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'uq_send_logs_lead_scenario_scheduled'"
    ))
    if result.fetchone():
        bind.execute(sa.text("ALTER TABLE send_logs DROP CONSTRAINT uq_send_logs_lead_scenario_scheduled"))
    
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name = 'templates' AND column_name = 'channel_type'"
    ))
    if not result.fetchone():
        bind.execute(sa.text("ALTER TABLE templates ADD COLUMN channel_type channeltype NOT NULL DEFAULT 'EMAIL'"))
    
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name = 'templates' AND column_name = 'message_text'"
    ))
    if not result.fetchone():
        bind.execute(sa.text("ALTER TABLE templates ADD COLUMN message_text TEXT"))
    
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name = 'templates' AND column_name = 'flex_message_json'"
    ))
    if not result.fetchone():
        bind.execute(sa.text("ALTER TABLE templates ADD COLUMN flex_message_json JSONB"))
    
    bind.execute(sa.text("ALTER TABLE templates ALTER COLUMN subject DROP NOT NULL"))
    bind.execute(sa.text("ALTER TABLE templates ALTER COLUMN body_html DROP NOT NULL"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'body_html',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('templates', 'subject',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('templates', 'flex_message_json')
    op.drop_column('templates', 'message_text')
    op.drop_column('templates', 'channel_type')
    op.create_unique_constraint(op.f('uq_send_logs_lead_scenario_scheduled'), 'send_logs', ['lead_id', 'scenario_id', 'scheduled_for'], postgresql_nulls_not_distinct=False)
    op.drop_column('send_logs', 'provider_message_id')
    op.drop_column('send_logs', 'channel')
    op.drop_column('leads', 'line_blocked')
    op.drop_index(op.f('ix_line_identities_line_user_id'), table_name='line_identities')
    op.drop_index(op.f('ix_line_identities_lead_id'), table_name='line_identities')
    op.drop_table('line_identities')
    # ### end Alembic commands ###
