"""add_scenario_segment_conditions

Revision ID: aec4bf5f60af
Revises: a1b2c3d4e5f6
Create Date: 2026-01-25 14:21:15.506637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec4bf5f60af'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('segment_graduation_year_from', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('segment_graduation_year_to', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('segment_grade_in', sa.Text(), nullable=True))
    op.add_column('scenarios', sa.Column('segment_prefecture', sa.String(length=50), nullable=True))
    op.add_column('scenarios', sa.Column('segment_tag', sa.String(length=255), nullable=True))
    op.add_column('scenarios', sa.Column('segment_school_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'segment_school_name')
    op.drop_column('scenarios', 'segment_tag')
    op.drop_column('scenarios', 'segment_prefecture')
    op.drop_column('scenarios', 'segment_grade_in')
    op.drop_column('scenarios', 'segment_graduation_year_to')
    op.drop_column('scenarios', 'segment_graduation_year_from')
    # ### end Alembic commands ###
