"""add external_id to leads

Revision ID: f1e28bda950c
Revises: 9b87b08ba3f6
Create Date: 2025-12-30 02:11:02.350539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1e28bda950c'
down_revision: Union[str, Sequence[str], None] = '9b87b08ba3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_leads_external_id'), 'leads', ['external_id'], unique=False)
    op.alter_column('templates', 'flex_message_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'flex_message_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_leads_external_id'), table_name='leads')
    op.drop_column('leads', 'external_id')
    # ### end Alembic commands ###
